pipeline {
    agent any

    parameters {
        choice(name: 'Environment', choices: ['Development', 'Production'], description: 'Choose the environment to build')
        choice(name: 'Branch', choices: ['main', 'development', 'Others'], description: 'Select branch')
        string(name: 'Others', defaultValue: '', description: 'Specify branch name if Others is selected')
    }

    environment {
        NETLIFY_AUTH_TOKEN = credentials('netlify-auth-token')
        DEV_SITE_ID = 'efd65b24-988f-43c8-be64-9a86aba14b42'
        PROD_SITE_ID = 'b75a440e-3888-4c72-83b1-76ea469517b7'
    }

    stages {

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Code Checkout') {
            steps {
                script {
                    if (params.Branch == 'Others' && !params.Others?.trim()) {
                        error "Branch Name is required when selected Others as Branch"
                    }

                    def branchToSelect = params.Branch == 'Others' ? params.Others.trim() : params.Branch

                    checkout scmGit(
                        branches: [[name: "*/${branchToSelect}"]], 
                        extensions: [], 
                        userRemoteConfigs: [[url: 'https://github.com/somjeet2000/ThinkPad-Client.git']]
                    )
                }
            }
        }

        stage('Install Dependencies & Build Application') {
            agent {
                docker {
                    image 'node:20-alpine'
                    args '--user root -v "$WORKSPACE:/workspace"'
                }
            }
            steps {
                script {
                    sh """
                        cd /workspace
                        rm -rf node_modules build
                        npm cache clean --force
                        npm ci

                        if [ "${params.Environment}" = "Development" ]; then
                            cp .env.development .env.production
                            echo '✅ Using Development Environment Variables'
                        else
                            cp .env.production .env.production
                            echo '✅ Using Production Environment Variables'
                        fi

                        CI=false npm run build
                    """
                    echo '✅ Project Built Successfully.'
                }
            }
        }

        stage('Deploy to Netlify Service') {
            agent {
                docker {
                    image 'node:20-alpine'
                    args '--user root -v "$WORKSPACE:/workspace"'
                }
            }
            steps {
                script {
                    sh """
                        cd /workspace
                        npm install -g netlify-cli
                        echo '✅ Netlify CLI Installed Successfully'

                        siteId=\$( [ "${params.Environment}" = "Development" ] && echo "${env.DEV_SITE_ID}" || echo "${env.PROD_SITE_ID}" )

                        netlify deploy --prod --auth ${NETLIFY_AUTH_TOKEN} --site \$siteId --dir build
                        echo "🚀 Deployed to ${params.Environment}."
                    """
                }
            }
        }
    }
}